package utils;

public enum TypeResponse {
    BAD_RESPONSE,
    USER_ALREADY_EXISTS,
    REGISTER,
    WRONG_PASSWORD,
    LOG_IN,
    OK,

    EMPTY_REGISTRATION,

    EMPTY_CONNECTION_WITH_SERVER,
    ALREADY_ACTIVE_SESSION;

}