package utils;

public enum TypeMessage {
    EMPTY_CONNECTION_WITH_SERVER,
    BAD_RESPONSE,
    LOG_IN,
    REGISTER,
    WRONG_PASSWORD,
    ALREADY_ACTIVE_SESSION,
    OK,
    EMPTY_REGISTRATION

}
